// Custom convention plugin - mainly composition of another plugins.
// Plugins that only reconfigure existing plugins are typically called 'convention plugin'.
plugins {
    id("application")
    id("my-java-base")
}

// Custom task to zip all jar files generated by this application.
tasks.register<Zip>("bundle") {
    // optionally we can group tasks
    group = "My group"
    description = "packages it all!"

    // zip the output of the 'jar' task.
    from(tasks.jar)
    // zip all the dependencies of 'jar' task. (commons.lang3 in our case).
    from(configurations.runtimeClasspath)

    // save output of this task (zip file) into build directory and create 'distribution' folder there.
    destinationDirectory.set(layout.buildDirectory.dir("distribution"))
}